# Generated by Django 4.1.7 on 2023-04-23 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'chemical_types',
            },
        ),
        migrations.CreateModel(
            name='Manufactures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'manufactures',
            },
        ),
        migrations.CreateModel(
            name='Chemicals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('cas', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('chemical_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defo_store.chemicaltypes')),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defo_store.manufactures')),
            ],
            options={
                'db_table': 'chemicals',
            },
        ),
        migrations.CreateModel(
            name='ChemicalPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='chemical_pictures/')),
                ('order', models.IntegerField()),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defo_store.chemicals')),
            ],
            options={
                'db_table': 'chemical_pictures',
                'ordering': ['order'],
            },
        ),
    ]
